force-app/main/default/objects/ErrorData__c/ErrorData__c.object-meta.xml
<CustomObject>
    <label>ErrorData</label>
    <nameField>
        <label>ErrorData Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorData__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorData__c/fields/zipcode__c.field-meta.xml
<CustomField>
    <fullName>zipcode__c</fullName>
    <label>zipcode</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/searchZipCode.cls
/**
 * description       : Class to store the error data
 * author            : jyothi.boddu@gmail.com
 * group             : 
 * last modified on  : 17-06-2023 
 * last modified by  : jyothi.boddu@gmail.com
 * Modifications Log 
 * Ver   Date          Author                        Modification
 * 1.0  17-06-2023     jyothi.boddu@gmail.com   Initial Version
**/
public without sharing class searchZipCode {

    @AuraEnabled
    public static void insertErr(String response, string zipcode) {

        System.debug('response ' + response + 'Zipcode ois ' + zipcode);

        ErrorData__c error = new ErrorData__c();
        error.Response__c = response;
        error.zipcode__c = zipcode;

        try{
            Insert error;
        }Catch(exception e){
            System.debug(e.getMessage());
        }

    }
}